# Generated by Django 3.2.11 on 2022-01-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
